"""remove_readmeurl_unique

Revision: 381ee8388179
Revises: 63911844305
Created: 2015-08-24 07:39:57.790255
"""

revision = '381ee8388179'
down_revision = '63911844305'

from alembic import op
from spire.schema.fields import *
from sqlalchemy import (Column, ForeignKey, ForeignKeyConstraint, PrimaryKeyConstraint,
    CheckConstraint, UniqueConstraint)
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter table workflow_mule drop constraint workflow_mule_readmeurl_key") 
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter table workflow_mule add constraint workflow_mule_readmeurl_key UNIQUE(readmeurl)") 
    ### end Alembic commands ###
